- name: Build Node Exporter
  shell: |
    mkdir -p /opt/node_exporter
    cd /opt/node_exporter
    cat > Dockerfile <<EOF
    FROM golang:1.21
    RUN git clone https://github.com/prometheus/node_exporter.git &&         cd node_exporter && make build
    CMD ["./node_exporter/node_exporter"]
    EOF
    docker build -t custom-node-exporter .

- name: Run Node Exporter container
  docker_container:
    name: node_exporter
    image: custom-node-exporter
    state: started
    restart_policy: always
    ports:
      - "9100:9100"
